services:
    # metricas:
    #     image: grafana/otel-lgtm:latest
    #     container_name: otel-lgtm
    #     ports:
    #         - 3000:3000 # Grafana (admin, admin)
    #         - 4317:4317 # Collector gRPC
    #         - 4318:4318 # Collector HTTP
    #         - 9090:9090 # Prometheus


    tracing:
        image: jaegertracing/all-in-one:latest
        container_name: jaeger
        ports:
            - 16686:16686 # Jaeger UI
            - 4317:4317 # Collector gRPC